### ISSUE TITLE
Restriction of max. body mass does not work

### ISSUE THREAD

**Issue by damariszurell** [MadingleyR/MadingleyR#2]
Dear Selwyn,

I have built a script for class to exemplify your Hoeks et al. (2020) study on large carnivore loss. I have largely followed case study 1 of this repository. However, the removal of large bodied cohorts and subsequent restriction of max. body mass does not seem to work, meaning that large body masses of carnivores are still occurring. I thought it might be some stochastic issue and ran the simulations for 500 years, still with the result that I had endotherm carnivore body masses of >300 kg.

Do you know what could be the problem? It seems that the restriction of spatial inputs has no effect. 
Or maybe I have overlooked something?

Here are the outputs after 50 years of simulation (when simulating 500 years, the body masses increase even more):
![grafik](https://user-images.githubusercontent.com/22585618/170820591-a2548925-255b-435d-a15c-20f892ae6478.png)

My session info is here:

<img width="668" alt="grafik" src="https://user-images.githubusercontent.com/22585618/170820455-c7bb2ab9-9e9a-4982-b921-a2c93e141a0e.png">

R script (full markdown here: https://damariszurell.github.io/CLEWS-EDB/12_Mad_carnivores.html):
[12_Mad_carnivores.txt](https://github.com/MadingleyR/MadingleyR/files/8790923/12_Mad_carnivores.txt)

Many thanks,
Damaris

**Comment by SHoeks** [comment]
Dear Damaris,

Thanks for your detailed question and for making me aware of this issue, the short answer is that I made a mixed up my own methods for controlling the maximum allowed body masses. In case study 1 it didn't show up and therefore I didn't realise it until now. My apologies for the inconvenience, I've fixed the case study description and code, see: https://github.com/MadingleyR/MadingleyR/blob/master/CaseStudies/CASESTUDY1.md. 

**More in depth explanation:**
When testing the package I found some issues with defining the maximum allowed body masses spatially. The problem had to do with the fact that large-bodied cohorts might move to a cell in which only smaller cohorts might be allowed to live. Technically there is no issue for that large-bodied cohort to be present there and feed, metabolised etc, however, when it wants to reproduce issues arise. During reproduction a new body mass for the juvenile cohort is sampled close to that of the parent cohort, this body mass value may not exceed the upper limit of the allowed body mass for that functional group. Therefore, the large-bodied cohort might not be able to reproduce in a cell with a very small body mass limit.

My solution was to use the spatial layers to seed the model, so cohorts are generated until the maximum defined in the spatial input raster, thus resulting in an initial state that has larger animals in the correct locations. During the simulation, however, these spatial raster are ignored and instead global values are used (not spatially explicit), these are defined in the cohort definitions (on of the inputs to the Madingley init and run functions). The main problem was that I forgot about this reasoning and failed to write down the correct method in the case study.

**Fix to your case study**
In regards to your example, removing large endothermic carnivores (>21 kg) from a simulation, the following code can be used to ensure large carnivores will no longer be present after the removal step (example for Bialowieza location only):

```r
dirpath = paste0("/Users/osx/Desktop/tmp")
library(MadingleyR)

# Spatial window Bialowieza:
sptl_bialowieza = c(20, 25, 50, 54) 

# Initialise models for the two locations
mdat_B = madingley_init(spatial_window = sptl_bialowieza)

# Run spin-up of 50 years for Bialowieza and for Serengeti
mres_spinup_B = madingley_run(madingley_data = mdat_B, 
                              years = 50,
                              out_dir=dirpath)

# Run control scenario for 50 years, note that simulations start from spinup results: 
mres_control_B = madingley_run(madingley_data = mres_spinup_B, 
                               years = 50,
                               out_dir=dirpath)

# Define new output
mres_removal_B = mres_spinup_B

# Remove large carnivores in Bialowieza
remove_idx_B = which(mres_removal_B$cohorts$AdultMass > 21000 & 
                       mres_removal_B$cohorts$FunctionalGroupIndex == 1)
mres_removal_B$cohorts = mres_removal_B$cohorts[-remove_idx_B, ]

# Define maximum body size of endotherm carnivores in the cohort definitions:
c_defs = madingley_inputs('cohort definition')
print(c_defs) # second row contains the endothermic carnivores
c_defs$PROPERTY_Maximum.mass[2] = 21000

# Run simulation, insert the cohort definitions to make sure large carnivores are limited to 21 kg:
mres_removal_B = madingley_run(madingley_data = mres_removal_B, 
                               cohort_def = c_defs,
                               years = 50,
                               out_dir=dirpath)

# Body mass check
plot_densities(mres_control_B)
plot_densities(mres_removal_B)
```

**Comment by damariszurell** [comment]
Dear Selwyn,

Thank you so much; this solved it!

Nevertheless, there seems to be a small glitch in the madingley_run() function when calling the input data "madingley_data". When initiating "cohort_def" in madingley_init() or when using the output of a previous run that had a specific manipulation of "cohort_def", then these are not taken into account when running madingley_run() but instead the default values are used. The default values for "cohort_def" are only overrun when defining them as argument in the madingley_run() function. I haven't checked the stock definition or model parameters. For the spatial inputs it works either way.

Thanks a lot for your quick help!
Best,
Damaris

**Comment by SHoeks** [comment]
Dear Damaris,

Thanks for noticing this bug, ```madingley_run()``` was indeed not using the cohort (and stock) definitions supplied by a previous model run or by ```madingley_init()``` (it was not using the definitions included in the ```madingley_data``` input argument). I've corrected this in the newest version of the package. 

Basically ```madingley_run()``` never has load the default definitions, because it always has to receive data from a previous ```madingley_run()``` or ```madingley_init()``` call. Only when the ```cohort_def ``` or ```stock_def``` arguments are used in ```madingley_run()``` it will overwrite the definitions found in ```madingley_data```. 

Hope this solves the issue,

Cheers, Selwyn

**Comment by damariszurell** [comment]
Dear Selwyn,

Perfect, thank you so much for your help!

Best,
Damaris
